---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.topic }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.topic }}-db
  template:
    metadata:
      labels:
        app: {{ .Values.topic }}-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: {{ .Values.topic }}
        - name: POSTGRES_USER
          value: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD